// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpOI-Vaqt-HWQmMh-y7MIxiT0H1LzGDu8',
    appId: '1:1087825495680:web:54dec4b88a7c062f56c865',
    messagingSenderId: '1087825495680',
    projectId: 'spotify-44046',
    authDomain: 'spotify-44046.firebaseapp.com',
    storageBucket: 'spotify-44046.appspot.com',
    measurementId: 'G-4T6KV8WTBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNuTXLnXmz6NdJSs8CGH00YeVW_3BBvQ',
    appId: '1:1087825495680:android:50053d06f9f8ae4256c865',
    messagingSenderId: '1087825495680',
    projectId: 'spotify-44046',
    storageBucket: 'spotify-44046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm6L-IWL46ChfVrRlQfSNPH1CccAi5njc',
    appId: '1:1087825495680:ios:77896c2d1fc39d4856c865',
    messagingSenderId: '1087825495680',
    projectId: 'spotify-44046',
    storageBucket: 'spotify-44046.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm6L-IWL46ChfVrRlQfSNPH1CccAi5njc',
    appId: '1:1087825495680:ios:77896c2d1fc39d4856c865',
    messagingSenderId: '1087825495680',
    projectId: 'spotify-44046',
    storageBucket: 'spotify-44046.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpOI-Vaqt-HWQmMh-y7MIxiT0H1LzGDu8',
    appId: '1:1087825495680:web:0b63cecf2d9a631756c865',
    messagingSenderId: '1087825495680',
    projectId: 'spotify-44046',
    authDomain: 'spotify-44046.firebaseapp.com',
    storageBucket: 'spotify-44046.appspot.com',
    measurementId: 'G-34EY188CXQ',
  );
}
